#! /usr/bin/env python

import sys
import os
import urlparse, urllib, os.path

if len(sys.argv) < 2:
    sys.stderr.write('Usage: fetch link ')
    sys.exit(1)

link=sys.argv[1]

print link

pathname = os.path.dirname(urllib.url2pathname(urlparse.urlparse(link).path))
filename = os.path.basename(link)

print pathname
print filename
print link


os.system("curl -o %s.html -O %s" %(filename,link))
os.system("pandoc -s --to rst %s.html -o x-%s.rst" % (filename,filename))

filename = "x-%s.rst" % filename

with open(filename) as f:
    content = f.readlines()


(junk, content)  = "".join(content).split("backlinks>`__")
(content, junk)  = "".join(content).split("-  `About </about>`__")

(content, junk)  = "".join(content).split("-  `Sponsors </sponsors>`__")


file = open(filename, 'wb')
file.write(content)
file.close()
