#! /usr/bin/env python

import sys
import os

if len(sys.argv) < 2:
    sys.stderr.write('Usage: fetch link ')
    sys.exit(1)

link=sys.argv[1]

print link

filename = "x-%s.rst" % link

os.system("curl -o %s.html -O https://portal.futuregrid.org/%s" %(link,link))
os.system("pandoc -s --to rst %s.html -o x-%s.rst" % (link,link))


with open(filename) as f:
    content = f.readlines()


(junk, content)  = "".join(content).split("backlinks>`__")
(content, junk)  = "".join(content).split("-  `About </about>`__")

(content, junk)  = "".join(content).split("-  `Sponsors </sponsors>`__")






file = open(filename, 'wb')
file.write(content)
file.close()
